version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = false
rainCulling = true
dontCull = []
useBlockStateCulling = false
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 1
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
arts_and_crafts = true
enderscape = true
oreganized = true
darkerdepths = true
farmersdelight = true
where_winds_blow = true
upgrade_aquatic = true
portablehole = true
field = true
nomansland = true
woodworks = true
curiosities = true
simulated = true
create = true
environmental = true
aeronautics = true
overgeared = true
brewinandchewin = true
abundant_atmosphere = true
clayworks = true
dungeonsdelight = true
caverns_and_chasms = true
atmospheric = true
minecraft = true
wholecloth = true
windswept_delights = true
adaptedmobs = true
sootychimneys = true
spawn = true
peaceless = true
abnormals_delight = true
powergrid = true
windswept = true
cookscollection = true
amendments = true
nirvana = true
heart_crystals = true
moonlight = true
modulation = true
alloyed = true
reliable_backpacks = true
brick_and_mortar = true
offroad = true
supplementaries = true
exposure = true
everycomp = true
