textures.1=2
biomes.1=snowy_plains snowy_taiga old_growth_spruce_taiga old_growth_pine_taiga taiga windswept_gravelly_hills windswept_forest windswept_hills snowy_slopes grove_meadow stony_peaks frozen_peaks jagged_peaks frozen_river ice_spikes

textures.2=3
biomes.2=savanna desert savanna_plateau windswept_savanna badlands wooded_badlands eroded_badlands jungle sparse_jungle bamboo_jungle